name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # This sets up Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this in your GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in your GitHub secrets

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-image:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
