name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # เช็คเอาท์โค้ดจาก repository

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    
    - name: Build and build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # สร้าง Docker image จากไฟล์ใน current directory
        file: ./Dockerfile  # กำหนดไฟล์ Dockerfile
        push: true  # Push Docker image ไปที่ Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/react-testgit:${{ github.sha }}  # ระบุชื่อและ tag ของ Docker image
